using System.Collections.Generic;

namespace WpfViews.Controls.IconFontWpfs
{
    public static class IconFontDataFactory
    {
        public static IDictionary<IconFontKind, string> Create()
        {
            return new Dictionary<IconFontKind, string>
            {
                {
                    IconFontKind.None,
                    ""
                },
                {
                    IconFontKind.Chizi,
                    "\ue792"
                },
                {
                    IconFontKind.fangdajing,
                    "\ue793"
                },
                {
                    IconFontKind.cexian,
                    "\ue794"
                },
                {
                    IconFontKind.navicon,
                    "\ue795"
                },
                {
                    IconFontKind.navicon1,
                    "\ue796"
                },
                {
                    IconFontKind.bozhuogongju,
                    "\ue797"
                },
                {
                    IconFontKind.Tucengguanli,
                    "\ue798"
                },
                {
                    IconFontKind.naicon,
                    "\ue799"
                },
                {
                    IconFontKind.logo,
                    "\ue79a"
                },
                {
                    IconFontKind.guanbi,
                    "\ue79b"
                },
                {
                    IconFontKind.zuixiaohua,
                    "\ue79c"
                },
                {
                    IconFontKind.zuidahua,
                    "\ue79d"
                },
                {
                    IconFontKind.lujing,
                    "\ue79e"
                },
                {
                    IconFontKind.chongzuo,
                    "\ue79f"
                },
                {
                    IconFontKind.chexiao,
                    "\ue7a0"
                },
                {
                    IconFontKind.paixu,
                    "\ue7a1"
                },
                {
                    IconFontKind.yincang,
                    "\ue7a2"
                },
                {
                    IconFontKind.plus,
                    "\ue7a3"
                },
                {
                    IconFontKind.footerdelete,
                    "\ue7a4"
                },
                {
                    IconFontKind.footerexport,
                    "\ue7a5"
                },
                {
                    IconFontKind.footersave,
                    "\ue7a6"
                },
                {
                    IconFontKind.tool_delete,
                    "\ue7a8"
                },
                {
                    IconFontKind.tool_combine,
                    "\ue7aa"
                },
                {
                    IconFontKind.tool_edit,
                    "\ue7ac"
                },
                {
                    IconFontKind.tool_move,
                    "\ue7ad"
                },
                {
                    IconFontKind.tool_fanxiang1,
                    "\ue7a9"
                },
                {
                    IconFontKind.tool_cut,
                    "\ue7a7"
                },
                {
                    IconFontKind.tool_rotate,
                    "\ue7ab"
                },
                {
                    IconFontKind.icon_,
                    "\ue7ae"
                },
                {
                    IconFontKind.icon_1,
                    "\ue7af"
                },
                {
                    IconFontKind.icon_2,
                    "\ue7b0"
                },
                {
                    IconFontKind.icon_3,
                    "\ue7b1"
                },
                {
                    IconFontKind.icon_4,
                    "\ue7b2"
                },
                {
                    IconFontKind.icon_5,
                    "\ue7b3"
                },
                {
                    IconFontKind.icon_6,
                    "\ue7b4"
                },
                {
                    IconFontKind.icon_selected,
                    "\ue7b5"
                },
                {
                    IconFontKind.huidian,
                    "\ue7b6"
                },
                {
                    IconFontKind.uploadicon,
                    "\ue7b7"
                },
                {
                    IconFontKind.icon_selected1,
                    "\ue7b8"
                },
                {
                    IconFontKind.selectfiles,
                    "\ue7b9"
                },
                {
                    IconFontKind.xuanzhuan,
                    "\ue7bc"
                },
                {
                    IconFontKind.kejian,
                    "\ue7bd"
                },
                {
                    IconFontKind.huimian,
                    "\ue7bb"
                }
            };
        }
    }
}